<?php

declare(strict_types=1);

namespace ZealPHP\MongoDB\GridFS;

use ZealPHP\MongoDB\Exception\RuntimeException;

use function bin2hex;
use function fopen;
use function in_array;
use function random_bytes;
use function stream_context_create;
use function stream_context_get_options;
use function stream_get_meta_data;
use function stream_get_wrappers;
use function stream_wrapper_register;
use function strlen;
use function substr;

use const SEEK_SET;

/**
 * Stream wrapper backing Bucket::openUploadStream() — buffers writes in
 * memory and performs the GridFS upload when the handle is closed
 * (`fclose()`), mirroring the official library's gridfs:// wrapper model.
 * The file id is pre-generated by the Bucket so it's known before close.
 */
// phpcs:disable PSR1.Methods.CamelCapsMethodName.NotCamelCaps -- stream_* names are PHP's streamWrapper interface contract
class UploadStreamWrapper
{
    public const PROTOCOL = 'zealgridfs';

    /** @var resource|null set by PHP on the instance */
    public $context;

    private Bucket $bucket;

    private string $filename;

    /** @var array<string, mixed> */
    private array $options;

    private string $buffer = '';

    private bool $uploaded = false;

    /**
     * @var array<string, mixed> open-stream token → pre-generated file id.
     * BOUNDED: every entry is removed in stream_close(), which PHP invokes
     * on fclose() AND on resource GC (abandoned streams) — no growth on
     * long-running workers. (A context-based design doesn't work: the fopen
     * context is not readable from OUTSIDE via the stream handle.)
     */
    private static array $ids = [];

    private string $token = '';

    /** @return resource a writable stream; fclose() performs the upload */
    public static function open(Bucket $bucket, string $filename, array $options, mixed $fileId)
    {
        if (! in_array(self::PROTOCOL, stream_get_wrappers(), true)) {
            stream_wrapper_register(self::PROTOCOL, self::class);
        }

        $token = bin2hex(random_bytes(8));
        self::$ids[$token] = $fileId;

        $context = stream_context_create([
            self::PROTOCOL => [
                'bucket' => $bucket,
                'filename' => $filename,
                'options' => $options,
            ],
        ]);

        // The token IS the path — recoverable from the resource via
        // stream_get_meta_data()['uri'] for getFileIdForStream().
        $stream = fopen(self::PROTOCOL . '://' . $token, 'wb', false, $context);
        if ($stream === false) {
            unset(self::$ids[$token]);

            throw new RuntimeException('Failed to open GridFS upload stream');
        }

        return $stream;
    }

    /** @param resource $stream */
    public static function idForStream($stream): mixed
    {
        $uri = stream_get_meta_data($stream)['uri'] ?? '';
        $token = substr($uri, strlen(self::PROTOCOL . '://'));

        return self::$ids[$token] ?? null;
    }

    public function stream_open(string $path, string $mode, int $flags, string|null &$openedPath): bool
    {
        $ctx = $this->context === null ? [] : stream_context_get_options($this->context);
        $opts = $ctx[self::PROTOCOL] ?? [];
        if (! isset($opts['bucket'], $opts['filename'])) {
            return false;
        }

        $this->bucket = $opts['bucket'];
        $this->filename = $opts['filename'];
        $this->options = $opts['options'] ?? [];
        $this->token = substr($path, strlen(self::PROTOCOL . '://'));

        return true;
    }

    public function stream_write(string $data): int
    {
        $this->buffer .= $data;

        return strlen($data);
    }

    public function stream_close(): void
    {
        if ($this->uploaded) {
            return;
        }

        $this->uploaded = true;
        $id = self::$ids[$this->token] ?? null;
        unset(self::$ids[$this->token]); // bounded-map guarantee — evict BEFORE upload (even on throw)
        if ($id !== null) {
            $this->options['_id'] = $id;
        }

        $this->bucket->uploadBytes($this->filename, $this->buffer, $this->options);
        $this->buffer = '';
    }

    public function stream_tell(): int
    {
        return strlen($this->buffer);
    }

    public function stream_eof(): bool
    {
        return true;
    }

    public function stream_flush(): bool
    {
        return true;
    }

    /** @return array<int|string, int> */
    public function stream_stat(): array
    {
        return ['size' => strlen($this->buffer)];
    }

    public function stream_read(string|int $count): string|false
    {
        return false; // write-only
    }

    public function stream_seek(int $offset, int $whence = SEEK_SET): bool
    {
        return false; // append-only, like the official upload stream
    }
}
