<?php

declare(strict_types=1);

namespace ZealPHP\MongoDB\GridFS;

use ZealPHP\MongoDB\Exception\RuntimeException;

use function fopen;
use function get_resource_id;
use function in_array;
use function stream_context_create;
use function stream_context_get_options;
use function stream_get_wrappers;
use function stream_wrapper_register;
use function strlen;

use const SEEK_SET;

/**
 * Stream wrapper backing Bucket::openUploadStream() — buffers writes in
 * memory and performs the GridFS upload when the handle is closed
 * (`fclose()`), mirroring the official library's gridfs:// wrapper model.
 * The file id is pre-generated by the Bucket so it's known before close.
 */
// phpcs:disable PSR1.Methods.CamelCapsMethodName.NotCamelCaps -- stream_* names are PHP's streamWrapper interface contract
class UploadStreamWrapper
{
    public const PROTOCOL = 'zealgridfs';

    /** @var resource|null set by PHP on the instance */
    public $context;

    private Bucket $bucket;

    private string $filename;

    /** @var array<string, mixed> */
    private array $options;

    private string $buffer = '';

    private bool $uploaded = false;

    /** @var array<int, mixed> resource id → pre-generated file id */
    private static array $streamIds = [];

    /** @return resource a writable stream; fclose() performs the upload */
    public static function open(Bucket $bucket, string $filename, array $options, mixed $fileId)
    {
        if (! in_array(self::PROTOCOL, stream_get_wrappers(), true)) {
            stream_wrapper_register(self::PROTOCOL, self::class);
        }

        $context = stream_context_create([
            self::PROTOCOL => [
                'bucket' => $bucket,
                'filename' => $filename,
                'options' => $options,
            ],
        ]);

        $stream = fopen(self::PROTOCOL . '://' . $filename, 'wb', false, $context);
        if ($stream === false) {
            throw new RuntimeException('Failed to open GridFS upload stream');
        }

        self::$streamIds[get_resource_id($stream)] = $fileId;

        return $stream;
    }

    /** @param resource $stream */
    public static function idForStream($stream): mixed
    {
        return self::$streamIds[get_resource_id($stream)] ?? null;
    }

    public function stream_open(string $path, string $mode, int $flags, string|null &$openedPath): bool
    {
        $ctx = $this->context === null ? [] : stream_context_get_options($this->context);
        $opts = $ctx[self::PROTOCOL] ?? [];
        if (! isset($opts['bucket'], $opts['filename'])) {
            return false;
        }

        $this->bucket = $opts['bucket'];
        $this->filename = $opts['filename'];
        $this->options = $opts['options'] ?? [];

        return true;
    }

    public function stream_write(string $data): int
    {
        $this->buffer .= $data;

        return strlen($data);
    }

    public function stream_close(): void
    {
        if ($this->uploaded) {
            return;
        }

        $this->uploaded = true;
        $this->bucket->uploadBytes($this->filename, $this->buffer, $this->options);
        $this->buffer = '';
    }

    public function stream_tell(): int
    {
        return strlen($this->buffer);
    }

    public function stream_eof(): bool
    {
        return true;
    }

    public function stream_flush(): bool
    {
        return true;
    }

    /** @return array<int|string, int> */
    public function stream_stat(): array
    {
        return ['size' => strlen($this->buffer)];
    }

    public function stream_read(string|int $count): string|false
    {
        return false; // write-only
    }

    public function stream_seek(int $offset, int $whence = SEEK_SET): bool
    {
        return false; // append-only, like the official upload stream
    }
}
